import { Inter } from "next/font/google";
import "./globals.css";
// add bootstrap css 
import 'bootstrap/dist/css/bootstrap.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <header>root layout</header> */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
